security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: ${NOTIFICATION_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /notifications
  port: 8000

remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! We''ve missed you here on PiggyMetrics. It''s time to check your budget statistics.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics reminder

backup:
  cron: 0 0 12 * * *
  email:
    text: "Howdy, {0}. Your account backup is ready.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics account backup
    attachment: backup.json

spring:
  data:
    mongodb:
      host: notification-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  mail:
    host: ${NOTIFICATION_EMAIL_HOST}
    port: ${NOTIFICATION_EMAIL_PORT}
    username: ${NOTIFICATION_EMAIL_USER}
    password: ${NOTIFICATION_EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: ${NOTIFICATION_EMAIL_PORT}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
